{"name": "test_mp_login[13812345678-246810-138123456781]", "status": "broken", "statusDetails": {"message": "NameError: name 'allure' is not defined", "trace": "self = <scripts.test_01_mp_login.TestMpLogin object at 0x109dcca10>\nusername = '13812345678', code = 246810, expect = 13812345678\n\n    @pytest.mark.parametrize(\"username, code, expect\", readyaml(\"mp_login.yml\"))\n    def test_mp_login(self, username, code, expect):\n    \n        try:\n            # 调用登录业务方法\n>           self.mp.page_mp_login(username, code)\n\ntest_01_mp_login.py:31: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <page.page_mp_login.PageMpLogin object at 0x109db8ad0>\nusername = '13812345678', code = 246810\n\n    def page_mp_login(self, username, code):\n        \"\"\"\n        调用相同页面的操作步骤\n        跨页面不考虑\n        :return:\n        \"\"\"\n>       self.page_input_username(username)\n\n../page/page_mp_login.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <page.page_mp_login.PageMpLogin object at 0x109db8ad0>\nusername = '13812345678'\n\n    def page_input_username(self, username):\n        # 读取__init__py配置内容\n>       self.base_input(page.mp_username, username)\n\n../page/page_mp_login.py:11: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <page.page_mp_login.PageMpLogin object at 0x109db8ad0>\nloc = ('css selector', \"[placeholder='请输入手机号']\"), value = '13812345678'\n\n    def base_input(self, loc, value):\n        \"\"\"\n    \n        :param loc: 元素定位信息\n        :param value:输入值\n        \"\"\"\n        # 获取元素\n>       el = self.base_find(loc)\n\n../base/base.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <page.page_mp_login.PageMpLogin object at 0x109db8ad0>\nloc = ('css selector', \"[placeholder='请输入手机号']\"), timeout = 30, poll = 0.5\n\n    def base_find(self, loc, timeout=30, poll=0.5):\n        \"\"\"\n    \n        :param loc: 格式为列表或元组 内容：元素定位信息\n        :param timeout: 查找元素超时时间 默认30s\n        :param poll: 查找元素频率 默认为0.5s\n        :return: 元素\n        \"\"\"\n        log.info(\"正在查找元素:{}\".format(loc))\n        return (WebDriverWait(self.driver, timeout=timeout, poll_frequency=poll)\n>               .until(lambda x: x.find_element(*loc)))\n\n../base/base.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"65928682af20180636561b87b450c0ab\")>\nmethod = <function Base.base_find.<locals>.<lambda> at 0x10a0c20e0>\nmessage = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n/usr/local/lib/python3.7/site-packages/selenium/webdriver/support/wait.py:80: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <scripts.test_01_mp_login.TestMpLogin object at 0x109dcca10>\nusername = '13812345678', code = 246810, expect = 13812345678\n\n    @pytest.mark.parametrize(\"username, code, expect\", readyaml(\"mp_login.yml\"))\n    def test_mp_login(self, username, code, expect):\n    \n        try:\n            # 调用登录业务方法\n            self.mp.page_mp_login(username, code)\n            # 断言\n            assert expect == self.mp.page_get_nickname()\n        except  Exception as e:\n            print(\"错误原因\",e)\n>           self.mp.base_get_img()\n\ntest_01_mp_login.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../base/base.py:68: in base_get_img\n    self.__base_write_img(file_path)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <page.page_mp_login.PageMpLogin object at 0x109db8ad0>\nfile_path = '/Users/lq/python/test/2020-09/uiAutoTestHmtt/image/20200917093213_.png'\n\n    def __base_write_img(self, file_path):\n        with open(file_path, \"rb\") as f:\n            file = f.read()\n>           allure.attach(\"错误原因\", file, allure.attach_type.PNG)\nE           NameError: name 'allure' is not defined\n\n../base/base.py:73: NameError"}, "attachments": [{"name": "log", "source": "8d0c9b1e-ab02-4da1-b7d4-bc73090a5c46-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'13812345678'"}, {"name": "code", "value": "246810"}, {"name": "expect", "value": "13812345678"}], "start": 1600306303193, "stop": 1600306355448, "uuid": "a96fab46-9e21-45fa-937e-b4094e087c4c", "historyId": "e2691b0cc571d95f051e682d035fdda1", "testCaseId": "0ef744100323d73770fc699b5f270c3a", "fullName": "scripts.test_01_mp_login.TestMpLogin#test_mp_login", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_01_mp_login"}, {"name": "subSuite", "value": "TestMpLogin"}, {"name": "host", "value": "promote.cache-dns.local"}, {"name": "thread", "value": "28247-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_01_mp_login"}]}