{"name": "test_mp_login[13812345678-246810-1381234567118]", "status": "broken", "statusDetails": {"message": "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte", "trace": "self = <scripts.test_01_mp_login.TestMpLogin object at 0x102b66cd0>\nusername = '13812345678', code = 246810, expect = '1381234567118'\n\n    @pytest.mark.parametrize(\"username, code, expect\", readyaml(\"mp_login.yml\"))\n    def test_mp_login(self, username, code, expect):\n        # 调用登录业务方法\n        self.mp.page_mp_login(username, code)\n        try:\n            # 断言\n>           assert expect == self.mp.page_get_nickname()\nE           AssertionError: assert '1381234567118' == '13812345678'\n\ntest_01_mp_login.py:31: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <scripts.test_01_mp_login.TestMpLogin object at 0x102b66cd0>\nusername = '13812345678', code = 246810, expect = '1381234567118'\n\n    @pytest.mark.parametrize(\"username, code, expect\", readyaml(\"mp_login.yml\"))\n    def test_mp_login(self, username, code, expect):\n        # 调用登录业务方法\n        self.mp.page_mp_login(username, code)\n        try:\n            # 断言\n            assert expect == self.mp.page_get_nickname()\n        except  Exception as e:\n            print(\"错误原因\",e)\n>           self.mp.base_get_img()\n\ntest_01_mp_login.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../base/base.py:68: in base_get_img\n    self.__base_write_img(file_path)\n../base/base.py:72: in __base_write_img\n    file = f.read()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <encodings.utf_8.IncrementalDecoder object at 0x1028e4410>\ninput = b'\\x89PNG\\r\\n\\x1a\\n\\x00\\x00\\x00\\rIHDR\\x00\\x00\\r \\x00\\x00\\x07\\x10\\x08\\x06\\x00\\x00\\x00y3\\x0e\\xd0\\x00\\x00\\x01*iCCPSkia\\x0...0H\\x80\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x14\\xfd\\x1fa\\xd6-\\x92w\\x8b\\\\\"\\x00\\x00\\x00\\x00IEND\\xaeB`\\x82'\nfinal = True\n\n    def decode(self, input, final=False):\n        # decode input (taking the buffer into account)\n        data = self.buffer + input\n>       (result, consumed) = self._buffer_decode(data, self.errors, final)\nE       UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte\n\n/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py:322: UnicodeDecodeError"}, "parameters": [{"name": "username", "value": "'13812345678'"}, {"name": "code", "value": "246810"}, {"name": "expect", "value": "'1381234567118'"}], "start": 1599814568035, "stop": 1599814598536, "uuid": "3a0fab57-a8f4-4062-a21c-2df28d9292cc", "historyId": "01ca993b08042689a3c1ac6e9760be33", "testCaseId": "0ef744100323d73770fc699b5f270c3a", "fullName": "scripts.test_01_mp_login.TestMpLogin#test_mp_login", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_01_mp_login"}, {"name": "subSuite", "value": "TestMpLogin"}, {"name": "host", "value": "promote.cache-dns.local"}, {"name": "thread", "value": "49678-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_01_mp_login"}]}